# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

# Included files
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Amcrest camera configuration
amcrest:
  - host: http://192.168.0.101/
    username: admin
    password: "roundpike%65delta"

# Bluetooth integration
bluetooth:

# Sensors (merged)
sensor:
  - platform: rest
    name: USA Air Quality Index
    resource: https://api.waqi.info/feed/salem/?token=9df775318d2c30747cda770f0b535ab3c7be89a4
    value_template: "{{ value_json.data.aqi }}"
    json_attributes:
      - data
    scan_interval: 600

  - platform: template
    sensors:
      nightstate:
        friendly_name: "Night State"
        value_template: >
          {% if is_state('sun.sun', 'below_horizon') %}
            1
          {% else %}
            0
          {% endif %}

      lightning_strike_latitude:
        friendly_name: "Lightning Strike Latitude"
        unit_of_measurement: "°"
        value_template: >
          {% set distance = states('sensor.home_lightning_distance') | float %}
          {% set azimuth = states('sensor.home_lightning_azimuth') | float %}
          {% set lat = state_attr('zone.home', 'latitude') | float %}
          {% set lon = state_attr('zone.home', 'longitude') | float %}
          {% set rad = 3.14159 / 180 %}
          {% set bearing = azimuth * rad %}
          {% set earth_radius = 6371 %}
          {% set d = distance / earth_radius %}
          {% set new_lat = asin(sin(lat * rad) * cos(d) + cos(lat * rad) * sin(d) * cos(bearing)) / rad %}
          {{ new_lat | round(5) }}

      lightning_strike_longitude:
        friendly_name: "Lightning Strike Longitude"
        unit_of_measurement: "°"
        value_template: >
          {% set distance = states('sensor.home_lightning_distance') | float %}
          {% set azimuth = states('sensor.home_lightning_azimuth') | float %}
          {% set lat = state_attr('zone.home', 'latitude') | float %}
          {% set lon = state_attr('zone.home', 'longitude') | float %}
          {% set rad = 3.14159 / 180 %}
          {% set bearing = azimuth * rad %}
          {% set earth_radius = 6371 %}
          {% set d = distance / earth_radius %}
          {% set new_lat = asin(sin(lat * rad) * cos(d) + cos(lat * rad) * sin(d) * cos(bearing)) %}
          {% set new_lon = lon * rad + atan2(sin(bearing) * sin(d) * cos(lat * rad), cos(d) - sin(lat * rad) * sin(new_lat)) %}
          {{ (new_lon / rad) | round(5) }}

# Input boolean
input_boolean:
  tablet_mode:
    name: Tablet Mode
    initial: true
